import { IFilm } from '../../lib/swapi-ts';

export const film1FullDetails: IFilm = {
  title: 'The Phantom Menace',
  episode_id: '1',
  opening_crawl:
    'Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....',
  director: 'George Lucas',
  producer: 'Rick McCallum',
  release_date: new Date(Date.parse('1999-05-19')),
  characters: [
    {
      name: 'C-3PO',
      height: '167',
      mass: '75',
      hair_color: 'n/a',
      skin_color: 'gold',
      eye_color: 'yellow',
      birth_year: '112BBY',
      gender: 'n/a',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/2/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-10T15:10:51.357000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.309000Z')),
      url: 'https://swapi.dev/api/people/2/',
    },
    {
      name: 'R2-D2',
      height: '96',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, blue',
      eye_color: 'red',
      birth_year: '33BBY',
      gender: 'n/a',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/2/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-10T15:11:50.376000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.311000Z')),
      url: 'https://swapi.dev/api/people/3/',
    },
    {
      name: 'Obi-Wan Kenobi',
      height: '182',
      mass: '77',
      hair_color: 'auburn, white',
      skin_color: 'fair',
      eye_color: 'blue-gray',
      birth_year: '57BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/20/',
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: ['https://swapi.dev/api/vehicles/38/'],
      starships: [
        'https://swapi.dev/api/starships/48/',
        'https://swapi.dev/api/starships/59/',
        'https://swapi.dev/api/starships/64/',
        'https://swapi.dev/api/starships/65/',
        'https://swapi.dev/api/starships/74/',
      ],
      created: new Date(Date.parse('2014-12-10T16:16:29.192000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.325000Z')),
      url: 'https://swapi.dev/api/people/10/',
    },
    {
      name: 'Anakin Skywalker',
      height: '188',
      mass: '84',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '41.9BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: [],
      vehicles: ['https://swapi.dev/api/vehicles/44/', 'https://swapi.dev/api/vehicles/46/'],
      starships: ['https://swapi.dev/api/starships/39/', 'https://swapi.dev/api/starships/59/', 'https://swapi.dev/api/starships/65/'],
      created: new Date(Date.parse('2014-12-10T16:20:44.310000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.327000Z')),
      url: 'https://swapi.dev/api/people/11/',
    },
    {
      name: 'Jabba Desilijic Tiure',
      height: '175',
      mass: '1,358',
      hair_color: 'n/a',
      skin_color: 'green-tan, brown',
      eye_color: 'orange',
      birth_year: '600BBY',
      gender: 'hermaphrodite',
      homeworld: 'https://swapi.dev/api/planets/24/',
      films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/5/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-10T17:11:31.638000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.338000Z')),
      url: 'https://swapi.dev/api/people/16/',
    },
    {
      name: 'Yoda',
      height: '66',
      mass: '17',
      hair_color: 'white',
      skin_color: 'green',
      eye_color: 'brown',
      birth_year: '896BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/28/',
      films: [
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: ['https://swapi.dev/api/species/6/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-15T12:26:01.042000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.345000Z')),
      url: 'https://swapi.dev/api/people/20/',
    },
    {
      name: 'Palpatine',
      height: '170',
      mass: '75',
      hair_color: 'grey',
      skin_color: 'pale',
      eye_color: 'yellow',
      birth_year: '82BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: [
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      species: [],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-15T12:48:05.971000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.347000Z')),
      url: 'https://swapi.dev/api/people/21/',
    },
    {
      name: 'Qui-Gon Jinn',
      height: '193',
      mass: '89',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '92BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/28/',
      films: ['https://swapi.dev/api/films/4/'],
      species: [],
      vehicles: ['https://swapi.dev/api/vehicles/38/'],
      starships: [],
      created: new Date(Date.parse('2014-12-19T16:54:53.618000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.375000Z')),
      url: 'https://swapi.dev/api/people/32/',
    },
    {
      name: 'Nute Gunray',
      height: '191',
      mass: '90',
      hair_color: 'none',
      skin_color: 'mottled green',
      eye_color: 'red',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/18/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/11/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:05:57.357000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.377000Z')),
      url: 'https://swapi.dev/api/people/33/',
    },
    {
      name: 'Finis Valorum',
      height: '170',
      mass: 'unknown',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '91BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/9/',
      films: ['https://swapi.dev/api/films/4/'],
      species: [],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:21:45.915000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.379000Z')),
      url: 'https://swapi.dev/api/people/34/',
    },
    {
      name: 'Padmé Amidala',
      height: '185',
      mass: '45',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '46BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/39/', 'https://swapi.dev/api/starships/49/', 'https://swapi.dev/api/starships/64/'],
      created: new Date(Date.parse('2014-12-19T17:28:26.926000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.381000Z')),
      url: 'https://swapi.dev/api/people/35/',
    },
    {
      name: 'Jar Jar Binks',
      height: '196',
      mass: '66',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'orange',
      birth_year: '52BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      species: ['https://swapi.dev/api/species/12/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:29:32.489000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.383000Z')),
      url: 'https://swapi.dev/api/people/36/',
    },
    {
      name: 'Roos Tarpals',
      height: '224',
      mass: '82',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'orange',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/12/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:32:56.741000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.385000Z')),
      url: 'https://swapi.dev/api/people/37/',
    },
    {
      name: 'Rugor Nass',
      height: '206',
      mass: 'unknown',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'orange',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/12/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:33:38.909000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.388000Z')),
      url: 'https://swapi.dev/api/people/38/',
    },
    {
      name: 'Ric Olié',
      height: '183',
      mass: 'unknown',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/'],
      species: [],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/40/'],
      created: new Date(Date.parse('2014-12-19T17:45:01.522000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.392000Z')),
      url: 'https://swapi.dev/api/people/39/',
    },
    {
      name: 'Watto',
      height: '137',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'blue, grey',
      eye_color: 'yellow',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/34/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      species: ['https://swapi.dev/api/species/13/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:48:54.647000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.395000Z')),
      url: 'https://swapi.dev/api/people/40/',
    },
    {
      name: 'Sebulba',
      height: '112',
      mass: '40',
      hair_color: 'none',
      skin_color: 'grey, red',
      eye_color: 'orange',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/35/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/14/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:53:02.586000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.397000Z')),
      url: 'https://swapi.dev/api/people/41/',
    },
    {
      name: 'Quarsh Panaka',
      height: '183',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '62BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/8/',
      films: ['https://swapi.dev/api/films/4/'],
      species: [],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:55:43.348000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.399000Z')),
      url: 'https://swapi.dev/api/people/42/',
    },
    {
      name: 'Shmi Skywalker',
      height: '163',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '72BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/1/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      species: [],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-19T17:57:41.191000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.401000Z')),
      url: 'https://swapi.dev/api/people/43/',
    },
    {
      name: 'Darth Maul',
      height: '175',
      mass: '80',
      hair_color: 'none',
      skin_color: 'red',
      eye_color: 'yellow',
      birth_year: '54BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/36/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/22/'],
      vehicles: ['https://swapi.dev/api/vehicles/42/'],
      starships: ['https://swapi.dev/api/starships/41/'],
      created: new Date(Date.parse('2014-12-19T18:00:41.929000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.403000Z')),
      url: 'https://swapi.dev/api/people/44/',
    },
    {
      name: 'Ayla Secura',
      height: '178',
      mass: '55',
      hair_color: 'none',
      skin_color: 'blue',
      eye_color: 'hazel',
      birth_year: '48BBY',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/37/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/15/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T09:48:01.172000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.409000Z')),
      url: 'https://swapi.dev/api/people/46/',
    },
    {
      name: 'Ratts Tyerel',
      height: '79',
      mass: '15',
      hair_color: 'none',
      skin_color: 'grey, blue',
      eye_color: 'unknown',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/38/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/16/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T09:53:15.086000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.410000Z')),
      url: 'https://swapi.dev/api/people/47/',
    },
    {
      name: 'Dud Bolt',
      height: '94',
      mass: '45',
      hair_color: 'none',
      skin_color: 'blue, grey',
      eye_color: 'yellow',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/39/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/17/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T09:57:31.858000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.414000Z')),
      url: 'https://swapi.dev/api/people/48/',
    },
    {
      name: 'Gasgano',
      height: '122',
      mass: 'unknown',
      hair_color: 'none',
      skin_color: 'white, blue',
      eye_color: 'black',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/40/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/18/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:02:12.223000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.416000Z')),
      url: 'https://swapi.dev/api/people/49/',
    },
    {
      name: 'Ben Quadinaros',
      height: '163',
      mass: '65',
      hair_color: 'none',
      skin_color: 'grey, green, yellow',
      eye_color: 'orange',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/41/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/19/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:08:33.777000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.417000Z')),
      url: 'https://swapi.dev/api/people/50/',
    },
    {
      name: 'Mace Windu',
      height: '188',
      mass: '84',
      hair_color: 'none',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '72BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/42/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: [],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:12:30.846000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.420000Z')),
      url: 'https://swapi.dev/api/people/51/',
    },
    {
      name: 'Ki-Adi-Mundi',
      height: '198',
      mass: '82',
      hair_color: 'white',
      skin_color: 'pale',
      eye_color: 'yellow',
      birth_year: '92BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/43/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/20/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:15:32.293000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.422000Z')),
      url: 'https://swapi.dev/api/people/52/',
    },
    {
      name: 'Kit Fisto',
      height: '196',
      mass: '87',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'black',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/44/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/21/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:18:57.202000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.424000Z')),
      url: 'https://swapi.dev/api/people/53/',
    },
    {
      name: 'Eeth Koth',
      height: '171',
      mass: 'unknown',
      hair_color: 'black',
      skin_color: 'brown',
      eye_color: 'brown',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/45/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/22/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:26:47.902000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.427000Z')),
      url: 'https://swapi.dev/api/people/54/',
    },
    {
      name: 'Adi Gallia',
      height: '184',
      mass: '50',
      hair_color: 'none',
      skin_color: 'dark',
      eye_color: 'blue',
      birth_year: 'unknown',
      gender: 'female',
      homeworld: 'https://swapi.dev/api/planets/9/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/23/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:29:11.661000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.432000Z')),
      url: 'https://swapi.dev/api/people/55/',
    },
    {
      name: 'Saesee Tiin',
      height: '188',
      mass: 'unknown',
      hair_color: 'none',
      skin_color: 'pale',
      eye_color: 'orange',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/47/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/24/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:32:11.669000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.434000Z')),
      url: 'https://swapi.dev/api/people/56/',
    },
    {
      name: 'Yarael Poof',
      height: '264',
      mass: 'unknown',
      hair_color: 'none',
      skin_color: 'white',
      eye_color: 'yellow',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/48/',
      films: ['https://swapi.dev/api/films/4/'],
      species: ['https://swapi.dev/api/species/25/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:34:48.725000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.437000Z')),
      url: 'https://swapi.dev/api/people/57/',
    },
    {
      name: 'Plo Koon',
      height: '188',
      mass: '80',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'black',
      birth_year: '22BBY',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/49/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      species: ['https://swapi.dev/api/species/26/'],
      vehicles: [],
      starships: ['https://swapi.dev/api/starships/48/'],
      created: new Date(Date.parse('2014-12-20T10:49:19.859000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.439000Z')),
      url: 'https://swapi.dev/api/people/58/',
    },
    {
      name: 'Mas Amedda',
      height: '196',
      mass: 'unknown',
      hair_color: 'none',
      skin_color: 'blue',
      eye_color: 'blue',
      birth_year: 'unknown',
      gender: 'male',
      homeworld: 'https://swapi.dev/api/planets/50/',
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      species: ['https://swapi.dev/api/species/27/'],
      vehicles: [],
      starships: [],
      created: new Date(Date.parse('2014-12-20T10:53:26.457000Z')),
      edited: new Date(Date.parse('2014-12-20T21:17:50.442000Z')),
      url: 'https://swapi.dev/api/people/59/',
    },
  ],
  planets: [
    {
      name: 'Tatooine',
      rotation_period: '23',
      orbital_period: '304',
      diameter: '10465',
      climate: 'arid',
      gravity: '1 standard',
      terrain: 'desert',
      surface_water: '1',
      population: '200000',
      residents: [
        'https://swapi.dev/api/people/1/',
        'https://swapi.dev/api/people/2/',
        'https://swapi.dev/api/people/4/',
        'https://swapi.dev/api/people/6/',
        'https://swapi.dev/api/people/7/',
        'https://swapi.dev/api/people/8/',
        'https://swapi.dev/api/people/9/',
        'https://swapi.dev/api/people/11/',
        'https://swapi.dev/api/people/43/',
        'https://swapi.dev/api/people/62/',
      ],
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      created: new Date(Date.parse('2014-12-09T13:50:49.641000Z')),
      edited: new Date(Date.parse('2014-12-20T20:58:18.411000Z')),
      url: 'https://swapi.dev/api/planets/1/',
    },
    {
      name: 'Naboo',
      rotation_period: '26',
      orbital_period: '312',
      diameter: '12120',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'grassy hills, swamps, forests, mountains',
      surface_water: '12',
      population: '4500000000',
      residents: [
        'https://swapi.dev/api/people/3/',
        'https://swapi.dev/api/people/21/',
        'https://swapi.dev/api/people/35/',
        'https://swapi.dev/api/people/36/',
        'https://swapi.dev/api/people/37/',
        'https://swapi.dev/api/people/38/',
        'https://swapi.dev/api/people/39/',
        'https://swapi.dev/api/people/42/',
        'https://swapi.dev/api/people/60/',
        'https://swapi.dev/api/people/61/',
        'https://swapi.dev/api/people/66/',
      ],
      films: ['https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-10T11:52:31.066000Z')),
      edited: new Date(Date.parse('2014-12-20T20:58:18.430000Z')),
      url: 'https://swapi.dev/api/planets/8/',
    },
    {
      name: 'Coruscant',
      rotation_period: '24',
      orbital_period: '368',
      diameter: '12240',
      climate: 'temperate',
      gravity: '1 standard',
      terrain: 'cityscape, mountains',
      surface_water: 'unknown',
      population: '1000000000000',
      residents: ['https://swapi.dev/api/people/34/', 'https://swapi.dev/api/people/55/', 'https://swapi.dev/api/people/74/'],
      films: ['https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-10T11:54:13.921000Z')),
      edited: new Date(Date.parse('2014-12-20T20:58:18.432000Z')),
      url: 'https://swapi.dev/api/planets/9/',
    },
  ],
  starships: [
    {
      name: 'Republic Cruiser',
      model: 'Consular-class cruiser',
      manufacturer: 'Corellian Engineering Corporation',
      cost_in_credits: 'unknown',
      length: '115',
      max_atmosphering_speed: '900',
      crew: '9',
      passengers: '16',
      cargo_capacity: 'unknown',
      consumables: 'unknown',
      hyperdrive_rating: '2.0',
      MGLT: 'unknown',
      starship_class: 'Space cruiser',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:01:31.488000Z')),
      edited: new Date(Date.parse('2014-12-20T21:23:49.912000Z')),
      url: 'https://swapi.dev/api/starships/31/',
    },
    {
      name: 'Droid control ship',
      model: 'Lucrehulk-class Droid Control Ship',
      manufacturer: 'Hoersch-Kessel Drive, Inc.',
      cost_in_credits: 'unknown',
      length: '3170',
      max_atmosphering_speed: 'n/a',
      crew: '175',
      passengers: '139000',
      cargo_capacity: '4000000000',
      consumables: '500 days',
      hyperdrive_rating: '2.0',
      MGLT: 'unknown',
      starship_class: 'Droid control ship',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-19T17:04:06.323000Z')),
      edited: new Date(Date.parse('2014-12-20T21:23:49.915000Z')),
      url: 'https://swapi.dev/api/starships/32/',
    },
    {
      name: 'Naboo fighter',
      model: 'N-1 starfighter',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps',
      cost_in_credits: '200000',
      length: '11',
      max_atmosphering_speed: '1100',
      crew: '1',
      passengers: '0',
      cargo_capacity: '65',
      consumables: '7 days',
      hyperdrive_rating: '1.0',
      MGLT: 'unknown',
      starship_class: 'Starfighter',
      pilots: ['https://swapi.dev/api/people/11/', 'https://swapi.dev/api/people/35/', 'https://swapi.dev/api/people/60/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      created: new Date(Date.parse('2014-12-19T17:39:17.582000Z')),
      edited: new Date(Date.parse('2014-12-20T21:23:49.917000Z')),
      url: 'https://swapi.dev/api/starships/39/',
    },
    {
      name: 'Naboo Royal Starship',
      model: 'J-type 327 Nubian royal starship',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives',
      cost_in_credits: 'unknown',
      length: '76',
      max_atmosphering_speed: '920',
      crew: '8',
      passengers: 'unknown',
      cargo_capacity: 'unknown',
      consumables: 'unknown',
      hyperdrive_rating: '1.8',
      MGLT: 'unknown',
      starship_class: 'yacht',
      pilots: ['https://swapi.dev/api/people/39/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:45:03.506000Z')),
      edited: new Date(Date.parse('2014-12-20T21:23:49.919000Z')),
      url: 'https://swapi.dev/api/starships/40/',
    },
    {
      name: 'Scimitar',
      model: 'Star Courier',
      manufacturer: 'Republic Sienar Systems',
      cost_in_credits: '55000000',
      length: '26.5',
      max_atmosphering_speed: '1180',
      crew: '1',
      passengers: '6',
      cargo_capacity: '2500000',
      consumables: '30 days',
      hyperdrive_rating: '1.5',
      MGLT: 'unknown',
      starship_class: 'Space Transport',
      pilots: ['https://swapi.dev/api/people/44/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T09:39:56.116000Z')),
      edited: new Date(Date.parse('2014-12-20T21:23:49.922000Z')),
      url: 'https://swapi.dev/api/starships/41/',
    },
  ],
  vehicles: [
    {
      name: 'Vulture Droid',
      model: 'Vulture-class droid starfighter',
      manufacturer: 'Haor Chall Engineering, Baktoid Armor Workshop',
      cost_in_credits: 'unknown',
      length: '3.5',
      max_atmosphering_speed: '1200',
      crew: '0',
      passengers: '0',
      cargo_capacity: '0',
      consumables: 'none',
      vehicle_class: 'starfighter',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-19T17:09:53.584000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.697000Z')),
      url: 'https://swapi.dev/api/vehicles/33/',
    },
    {
      name: 'Multi-Troop Transport',
      model: 'Multi-Troop Transport',
      manufacturer: 'Baktoid Armor Workshop',
      cost_in_credits: '138000',
      length: '31',
      max_atmosphering_speed: '35',
      crew: '4',
      passengers: '112',
      cargo_capacity: '12000',
      consumables: 'unknown',
      vehicle_class: 'repulsorcraft',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:12:04.400000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.700000Z')),
      url: 'https://swapi.dev/api/vehicles/34/',
    },
    {
      name: 'Armored Assault Tank',
      model: 'Armoured Assault Tank',
      manufacturer: 'Baktoid Armor Workshop',
      cost_in_credits: 'unknown',
      length: '9.75',
      max_atmosphering_speed: '55',
      crew: '4',
      passengers: '6',
      cargo_capacity: 'unknown',
      consumables: 'unknown',
      vehicle_class: 'repulsorcraft',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:13:29.799000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.703000Z')),
      url: 'https://swapi.dev/api/vehicles/35/',
    },
    {
      name: 'Single Trooper Aerial Platform',
      model: 'Single Trooper Aerial Platform',
      manufacturer: 'Baktoid Armor Workshop',
      cost_in_credits: '2500',
      length: '2',
      max_atmosphering_speed: '400',
      crew: '1',
      passengers: '0',
      cargo_capacity: 'none',
      consumables: 'none',
      vehicle_class: 'repulsorcraft',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:15:09.511000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.705000Z')),
      url: 'https://swapi.dev/api/vehicles/36/',
    },
    {
      name: 'C-9979 landing craft',
      model: 'C-9979 landing craft',
      manufacturer: 'Haor Chall Engineering',
      cost_in_credits: '200000',
      length: '210',
      max_atmosphering_speed: '587',
      crew: '140',
      passengers: '284',
      cargo_capacity: '1800000',
      consumables: '1 day',
      vehicle_class: 'landing craft',
      pilots: [],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:20:36.373000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.707000Z')),
      url: 'https://swapi.dev/api/vehicles/37/',
    },
    {
      name: 'Tribubble bongo',
      model: 'Tribubble bongo',
      manufacturer: 'Otoh Gunga Bongameken Cooperative',
      cost_in_credits: 'unknown',
      length: '15',
      max_atmosphering_speed: '85',
      crew: '1',
      passengers: '2',
      cargo_capacity: '1600',
      consumables: 'unknown',
      vehicle_class: 'submarine',
      pilots: ['https://swapi.dev/api/people/10/', 'https://swapi.dev/api/people/32/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:37:37.924000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.710000Z')),
      url: 'https://swapi.dev/api/vehicles/38/',
    },
    {
      name: 'Sith speeder',
      model: 'FC-20 speeder bike',
      manufacturer: 'Razalon',
      cost_in_credits: '4000',
      length: '1.5',
      max_atmosphering_speed: '180',
      crew: '1',
      passengers: '0',
      cargo_capacity: '2',
      consumables: 'unknown',
      vehicle_class: 'speeder',
      pilots: ['https://swapi.dev/api/people/44/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T10:09:56.095000Z')),
      edited: new Date(Date.parse('2014-12-20T21:30:21.712000Z')),
      url: 'https://swapi.dev/api/vehicles/42/',
    },
  ],
  species: [
    {
      name: 'Human',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'caucasian, black, asian, hispanic',
      hair_colors: 'blonde, brown, black, red',
      eye_colors: 'brown, blue, green, hazel, grey, amber',
      average_lifespan: '120',
      homeworld: 'https://swapi.dev/api/planets/9/',
      language: 'Galactic Basic',
      people: ['https://swapi.dev/api/people/66/', 'https://swapi.dev/api/people/67/', 'https://swapi.dev/api/people/68/', 'https://swapi.dev/api/people/74/'],
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      created: new Date(Date.parse('2014-12-10T13:52:11.567000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.136000Z')),
      url: 'https://swapi.dev/api/species/1/',
    },
    {
      name: 'Droid',
      classification: 'artificial',
      designation: 'sentient',
      average_height: 'n/a',
      skin_colors: 'n/a',
      hair_colors: 'n/a',
      eye_colors: 'n/a',
      average_lifespan: 'indefinite',
      homeworld: null,
      language: 'n/a',
      people: ['https://swapi.dev/api/people/2/', 'https://swapi.dev/api/people/3/', 'https://swapi.dev/api/people/8/', 'https://swapi.dev/api/people/23/'],
      films: [
        'https://swapi.dev/api/films/1/',
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      created: new Date(Date.parse('2014-12-10T15:16:16.259000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.139000Z')),
      url: 'https://swapi.dev/api/species/2/',
    },
    {
      name: "Yoda's species",
      classification: 'mammal',
      designation: 'sentient',
      average_height: '66',
      skin_colors: 'green, yellow',
      hair_colors: 'brown, white',
      eye_colors: 'brown, green, yellow',
      average_lifespan: '900',
      homeworld: 'https://swapi.dev/api/planets/28/',
      language: 'Galactic basic',
      people: ['https://swapi.dev/api/people/20/'],
      films: [
        'https://swapi.dev/api/films/2/',
        'https://swapi.dev/api/films/3/',
        'https://swapi.dev/api/films/4/',
        'https://swapi.dev/api/films/5/',
        'https://swapi.dev/api/films/6/',
      ],
      created: new Date(Date.parse('2014-12-15T12:27:22.877000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.148000Z')),
      url: 'https://swapi.dev/api/species/6/',
    },
    {
      name: 'Neimodian',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'grey, green',
      hair_colors: 'none',
      eye_colors: 'red, pink',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/18/',
      language: 'Neimoidia',
      people: ['https://swapi.dev/api/people/33/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:07:31.319000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.160000Z')),
      url: 'https://swapi.dev/api/species/11/',
    },
    {
      name: 'Gungan',
      classification: 'amphibian',
      designation: 'sentient',
      average_height: '190',
      skin_colors: 'brown, green',
      hair_colors: 'none',
      eye_colors: 'orange',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/8/',
      language: 'Gungan basic',
      people: ['https://swapi.dev/api/people/36/', 'https://swapi.dev/api/people/37/', 'https://swapi.dev/api/people/38/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      created: new Date(Date.parse('2014-12-19T17:30:37.341000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.163000Z')),
      url: 'https://swapi.dev/api/species/12/',
    },
    {
      name: 'Toydarian',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '120',
      skin_colors: 'blue, green, grey',
      hair_colors: 'none',
      eye_colors: 'yellow',
      average_lifespan: '91',
      homeworld: 'https://swapi.dev/api/planets/34/',
      language: 'Toydarian',
      people: ['https://swapi.dev/api/people/40/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/'],
      created: new Date(Date.parse('2014-12-19T17:48:56.893000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.165000Z')),
      url: 'https://swapi.dev/api/species/13/',
    },
    {
      name: 'Dug',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '100',
      skin_colors: 'brown, purple, grey, red',
      hair_colors: 'none',
      eye_colors: 'yellow, blue',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/35/',
      language: 'Dugese',
      people: ['https://swapi.dev/api/people/41/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-19T17:53:11.214000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.167000Z')),
      url: 'https://swapi.dev/api/species/14/',
    },
    {
      name: "Twi'lek",
      classification: 'mammals',
      designation: 'sentient',
      average_height: '200',
      skin_colors: 'orange, yellow, blue, green, pink, purple, tan',
      hair_colors: 'none',
      eye_colors: 'blue, brown, orange, pink',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/37/',
      language: "Twi'leki",
      people: ['https://swapi.dev/api/people/45/', 'https://swapi.dev/api/people/46/'],
      films: ['https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T09:48:02.406000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.169000Z')),
      url: 'https://swapi.dev/api/species/15/',
    },
    {
      name: 'Aleena',
      classification: 'reptile',
      designation: 'sentient',
      average_height: '80',
      skin_colors: 'blue, gray',
      hair_colors: 'none',
      eye_colors: 'unknown',
      average_lifespan: '79',
      homeworld: 'https://swapi.dev/api/planets/38/',
      language: 'Aleena',
      people: ['https://swapi.dev/api/people/47/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T09:53:16.481000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.171000Z')),
      url: 'https://swapi.dev/api/species/16/',
    },
    {
      name: 'Vulptereen',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '100',
      skin_colors: 'grey',
      hair_colors: 'none',
      eye_colors: 'yellow',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/39/',
      language: 'vulpterish',
      people: ['https://swapi.dev/api/people/48/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T09:57:33.128000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.173000Z')),
      url: 'https://swapi.dev/api/species/17/',
    },
    {
      name: 'Xexto',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '125',
      skin_colors: 'grey, yellow, purple',
      hair_colors: 'none',
      eye_colors: 'black',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/40/',
      language: 'Xextese',
      people: ['https://swapi.dev/api/people/49/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T10:02:13.915000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.175000Z')),
      url: 'https://swapi.dev/api/species/18/',
    },
    {
      name: 'Toong',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '200',
      skin_colors: 'grey, green, yellow',
      hair_colors: 'none',
      eye_colors: 'orange',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/41/',
      language: 'Tundan',
      people: ['https://swapi.dev/api/people/50/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:08:36.795000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.177000Z')),
      url: 'https://swapi.dev/api/species/19/',
    },
    {
      name: 'Cerean',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '200',
      skin_colors: 'pale pink',
      hair_colors: 'red, blond, black, white',
      eye_colors: 'hazel',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/43/',
      language: 'Cerean',
      people: ['https://swapi.dev/api/people/52/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:15:33.765000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.179000Z')),
      url: 'https://swapi.dev/api/species/20/',
    },
    {
      name: 'Nautolan',
      classification: 'amphibian',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'green, blue, brown, red',
      hair_colors: 'none',
      eye_colors: 'black',
      average_lifespan: '70',
      homeworld: 'https://swapi.dev/api/planets/44/',
      language: 'Nautila',
      people: ['https://swapi.dev/api/people/53/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T10:18:58.610000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.181000Z')),
      url: 'https://swapi.dev/api/species/21/',
    },
    {
      name: 'Zabrak',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'pale, brown, red, orange, yellow',
      hair_colors: 'black',
      eye_colors: 'brown, orange',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/45/',
      language: 'Zabraki',
      people: ['https://swapi.dev/api/people/44/', 'https://swapi.dev/api/people/54/'],
      films: ['https://swapi.dev/api/films/4/'],
      created: new Date(Date.parse('2014-12-20T10:26:59.894000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.183000Z')),
      url: 'https://swapi.dev/api/species/22/',
    },
    {
      name: 'Tholothian',
      classification: 'mammal',
      designation: 'sentient',
      average_height: 'unknown',
      skin_colors: 'dark',
      hair_colors: 'unknown',
      eye_colors: 'blue, indigo',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/46/',
      language: 'unknown',
      people: ['https://swapi.dev/api/people/55/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:29:13.798000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.186000Z')),
      url: 'https://swapi.dev/api/species/23/',
    },
    {
      name: 'Iktotchi',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'pink',
      hair_colors: 'none',
      eye_colors: 'orange',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/47/',
      language: 'Iktotchese',
      people: ['https://swapi.dev/api/people/56/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:32:13.046000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.188000Z')),
      url: 'https://swapi.dev/api/species/24/',
    },
    {
      name: 'Quermian',
      classification: 'mammal',
      designation: 'sentient',
      average_height: '240',
      skin_colors: 'white',
      hair_colors: 'none',
      eye_colors: 'yellow',
      average_lifespan: '86',
      homeworld: 'https://swapi.dev/api/planets/48/',
      language: 'Quermian',
      people: ['https://swapi.dev/api/people/57/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:34:50.827000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.189000Z')),
      url: 'https://swapi.dev/api/species/25/',
    },
    {
      name: 'Kel Dor',
      classification: 'unknown',
      designation: 'sentient',
      average_height: '180',
      skin_colors: 'peach, orange, red',
      hair_colors: 'none',
      eye_colors: 'black, silver',
      average_lifespan: '70',
      homeworld: 'https://swapi.dev/api/planets/49/',
      language: 'Kel Dor',
      people: ['https://swapi.dev/api/people/58/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:49:21.692000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.191000Z')),
      url: 'https://swapi.dev/api/species/26/',
    },
    {
      name: 'Chagrian',
      classification: 'amphibian',
      designation: 'sentient',
      average_height: '190',
      skin_colors: 'blue',
      hair_colors: 'none',
      eye_colors: 'blue',
      average_lifespan: 'unknown',
      homeworld: 'https://swapi.dev/api/planets/50/',
      language: 'Chagria',
      people: ['https://swapi.dev/api/people/59/'],
      films: ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/6/'],
      created: new Date(Date.parse('2014-12-20T10:53:28.795000Z')),
      edited: new Date(Date.parse('2014-12-20T21:36:42.193000Z')),
      url: 'https://swapi.dev/api/species/27/',
    },
  ],
  created: new Date(Date.parse('2014-12-19T16:52:55.740000Z')),
  edited: new Date(Date.parse('2014-12-20T10:54:07.216000Z')),
  url: 'https://swapi.dev/api/films/4/',
};

export const film1NoDetails: IFilm = {
  title: 'The Phantom Menace',
  episode_id: '1',
  opening_crawl:
    'Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....',
  director: 'George Lucas',
  producer: 'Rick McCallum',
  release_date: new Date(Date.parse('1999-05-19')),
  characters: [
    'https://swapi.dev/api/people/2/',
    'https://swapi.dev/api/people/3/',
    'https://swapi.dev/api/people/10/',
    'https://swapi.dev/api/people/11/',
    'https://swapi.dev/api/people/16/',
    'https://swapi.dev/api/people/20/',
    'https://swapi.dev/api/people/21/',
    'https://swapi.dev/api/people/32/',
    'https://swapi.dev/api/people/33/',
    'https://swapi.dev/api/people/34/',
    'https://swapi.dev/api/people/35/',
    'https://swapi.dev/api/people/36/',
    'https://swapi.dev/api/people/37/',
    'https://swapi.dev/api/people/38/',
    'https://swapi.dev/api/people/39/',
    'https://swapi.dev/api/people/40/',
    'https://swapi.dev/api/people/41/',
    'https://swapi.dev/api/people/42/',
    'https://swapi.dev/api/people/43/',
    'https://swapi.dev/api/people/44/',
    'https://swapi.dev/api/people/46/',
    'https://swapi.dev/api/people/47/',
    'https://swapi.dev/api/people/48/',
    'https://swapi.dev/api/people/49/',
    'https://swapi.dev/api/people/50/',
    'https://swapi.dev/api/people/51/',
    'https://swapi.dev/api/people/52/',
    'https://swapi.dev/api/people/53/',
    'https://swapi.dev/api/people/54/',
    'https://swapi.dev/api/people/55/',
    'https://swapi.dev/api/people/56/',
    'https://swapi.dev/api/people/57/',
    'https://swapi.dev/api/people/58/',
    'https://swapi.dev/api/people/59/',
  ],
  planets: ['https://swapi.dev/api/planets/1/', 'https://swapi.dev/api/planets/8/', 'https://swapi.dev/api/planets/9/'],
  starships: [
    'https://swapi.dev/api/starships/31/',
    'https://swapi.dev/api/starships/32/',
    'https://swapi.dev/api/starships/39/',
    'https://swapi.dev/api/starships/40/',
    'https://swapi.dev/api/starships/41/',
  ],
  vehicles: [
    'https://swapi.dev/api/vehicles/33/',
    'https://swapi.dev/api/vehicles/34/',
    'https://swapi.dev/api/vehicles/35/',
    'https://swapi.dev/api/vehicles/36/',
    'https://swapi.dev/api/vehicles/37/',
    'https://swapi.dev/api/vehicles/38/',
    'https://swapi.dev/api/vehicles/42/',
  ],
  species: [
    'https://swapi.dev/api/species/1/',
    'https://swapi.dev/api/species/2/',
    'https://swapi.dev/api/species/6/',
    'https://swapi.dev/api/species/11/',
    'https://swapi.dev/api/species/12/',
    'https://swapi.dev/api/species/13/',
    'https://swapi.dev/api/species/14/',
    'https://swapi.dev/api/species/15/',
    'https://swapi.dev/api/species/16/',
    'https://swapi.dev/api/species/17/',
    'https://swapi.dev/api/species/18/',
    'https://swapi.dev/api/species/19/',
    'https://swapi.dev/api/species/20/',
    'https://swapi.dev/api/species/21/',
    'https://swapi.dev/api/species/22/',
    'https://swapi.dev/api/species/23/',
    'https://swapi.dev/api/species/24/',
    'https://swapi.dev/api/species/25/',
    'https://swapi.dev/api/species/26/',
    'https://swapi.dev/api/species/27/',
  ],
  created: new Date(Date.parse('2014-12-19T16:52:55.740000Z')),
  edited: new Date(Date.parse('2014-12-20T10:54:07.216000Z')),
  url: 'https://swapi.dev/api/films/4/',
};
