/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IFilm } from "swapi-ts";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppRoot {
    }
    interface FilmsDetails {
        "films": IFilm[];
        "match": MatchResults;
    }
    interface FilmsList {
        "films": IFilm[];
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLFilmsDetailsElement extends Components.FilmsDetails, HTMLStencilElement {
    }
    var HTMLFilmsDetailsElement: {
        prototype: HTMLFilmsDetailsElement;
        new (): HTMLFilmsDetailsElement;
    };
    interface HTMLFilmsListElement extends Components.FilmsList, HTMLStencilElement {
    }
    var HTMLFilmsListElement: {
        prototype: HTMLFilmsListElement;
        new (): HTMLFilmsListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "films-details": HTMLFilmsDetailsElement;
        "films-list": HTMLFilmsListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface FilmsDetails {
        "films"?: IFilm[];
        "match"?: MatchResults;
    }
    interface FilmsList {
        "films"?: IFilm[];
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "films-details": FilmsDetails;
        "films-list": FilmsList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "films-details": LocalJSX.FilmsDetails & JSXBase.HTMLAttributes<HTMLFilmsDetailsElement>;
            "films-list": LocalJSX.FilmsList & JSXBase.HTMLAttributes<HTMLFilmsListElement>;
        }
    }
}
